-- ============================================================
-- [SUPERSEDED] 01_users.sql — 已被 sql/user/user.sql 替代
-- 本文件保留仅供历史参考。所有用户相关 DDL 请参见 user/user.sql
-- ============================================================
-- 旧版 user_account, user_profile, user_settings, refresh_tokens
-- 已于 2025-07 重构为 v2 版本
