-- ============================================================
-- [SUPERSEDED] 06_avatars.sql — character_avatar + pixel_avatars 已合并为 user_avatar
-- 本文件保留仅供历史参考。新 DDL 请参见 user/user.sql
-- ============================================================
